networks:
  chat-network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_HIPE_COMPILE: 1
    volumes:
      - ./infrastructure/rabbitmq/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    networks:
      - chat-network

  postgres:
    image: postgres:17.5-alpine
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./infrastructure/postgres/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - chat-network

  redis:
    image: redis:8.0-alpine
    hostname: redis
    container_name: redis
    restart: unless-stopped
    env_file: .env
    command: redis-server --requirepass $REDIS_PASSWORD
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./infrastructure/redis/redis-data:/var/lib/redis
      - ./infrastructure/redis/redis-full.conf:/usr/local/etc/redis/redis-full.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - chat-network

  fusionauth-db:
    image: postgres:17.5-alpine
    hostname: fusionauth-db
    container_name: fusionauth-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=$FUSIONAUTH_DB
      - POSTGRES_USER=$FUSIONAUTH_DB_ROOT_USER
      - POSTGRES_PASSWORD=$FUSIONAUTH_DB_ROOT_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./infrastructure/fusionauth/database/data:/var/lib/postgresql/data
    ports:
      - "${FUSIONAUTH_DB_PORT}:5432"
    networks:
      - chat-network

  fusionauth:
    image: fusionauth/fusionauth-app:1.57.1
    hostname: fusionauth
    container_name: fusionauth
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=jdbc:postgresql://fusionauth-db:5432/${FUSIONAUTH_DB}
      - DATABASE_ROOT_USERNAME=${FUSIONAUTH_DB_ROOT_USER}
      - DATABASE_ROOT_PASSWORD=${FUSIONAUTH_DB_ROOT_PASSWORD}
      - DATABASE_USERNAME=${FUSIONAUTH_DB_USER}
      - DATABASE_PASSWORD=${FUSIONAUTH_DB_PASSWORD}
      - FUSIONAUTH_APP_KICKSTART_FILE=${FUSIONAUTH_APP_KICKSTART_FILE}
      - FUSIONAUTH_APP_MEMORY=${FUSIONAUTH_APP_MEMORY}
      - FUSIONAUTH_APP_RUNTIME_MODE=${FUSIONAUTH_APP_RUNTIME_MODE}
      - FUSIONAUTH_APP_URL=http://fusionauth:9011
      - SEARCH_TYPE=${FUSIONAUTH_SEARCH_TYPE}
    healthcheck:
      test: curl --silent --fail http://localhost:9011/api/status -o /dev/null -w "%{http_code}"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${FUSIONAUTH_APP_PORT}:9011"
    volumes:
      - ./infrastructure/fusionauth/config:/usr/local/fusionauth/config
      - ./infrastructure/fusionauth/kickstart:/usr/local/fusionauth/kickstart
      - ./infrastructure/fusionauth/plugins:/usr/local/fusionauth/plugins
    networks:
      - chat-network

