networks:
  chat-network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_HIPE_COMPILE: 1
    volumes:
      - ./infrastructure/rabbitmq/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    networks:
      - chat-network

  postgres:
    image: postgres:17.5-alpine
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./infrastructure/postgres/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - chat-network

  redis:
    image: redis:8.0-alpine
    hostname: redis
    container_name: redis
    restart: unless-stopped
    env_file: .env
    command: redis-server --requirepass $REDIS_PASSWORD
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./infrastructure/redis/redis-data:/var/lib/redis
      - ./infrastructure/redis/redis-full.conf:/usr/local/etc/redis/redis-full.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - chat-network
